#!/usr/bin/env python
"""
Compute page-level CER, SpACER, and CDD for all (parsing_model, ocr_model) pairs.

Reference (GT) text comes from gt_ssu_bboxes.csv (generated by extract_ssu_text.py),
which contains both bounding boxes and gt_text for every SSU region.  Regions are
ordered by (ssu_n, y, x) to form the page-level reference string.

Hypothesis text is the model OCR output:
  - pm="gt"  : OCR run on GT regions (gt_ocr_df), ordered by (ssu_n, y, x).
                CER here reflects pure OCR error — sanity check, should be low.
  - pm!="gt" : OCR run on predicted regions, boxes matched to GT SSUs by canvas
                rasterisation then ordered by (ssu_n, pred_box_y, pred_box_x).

Page-level text strings are also written to data/results_spiritualist/page_text/
for visual inspection.

Output: data/results_spiritualist/page_level_cer_comparison.parquet
"""

import re
import sys
import unicodedata
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "cotescore/src"))

from cotescore import cdd_decomp, spacer
from cotescore.adapters import boxes_to_gt_ssu_map
from jiwer import cer as jiwer_cer

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_SSU_CSV = _REPO / "data/spiritualist/gt_ssu_bboxes.csv"
_OCR_DIR       = _REPO / "data/results_spiritualist/ocr"
_OUT           = _REPO / "data/results_spiritualist/page_level_cer_comparison.parquet"
_TEXT_GT_DIR   = _REPO / "data/results_spiritualist/page_text/gt"
_TEXT_PRED_DIR = _REPO / "data/results_spiritualist/page_text/pred"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _normalize_quotes(text: str) -> str:
    text = re.sub(r'[\u2018\u2019\u201a\u201b\u2039\u203a`]', "'", text)
    text = re.sub(r'[\u201c\u201d\u201e\u201f\u00ab\u00bb]', '"', text)
    return text


def _normalize_dashes(text: str) -> str:
    return re.sub(r'[\u2013\u2014\u2015\u2012]', '-', text)


def normalize_for_cer(text: str) -> str:
    text = text.lower()
    text = unicodedata.normalize('NFKC', text)
    text = _normalize_quotes(text)
    text = _normalize_dashes(text)
    text = text.replace('\xa0', ' ')
    text = re.sub(r'(?<!\n)\n(?!\n)', ' ', text)
    text = re.sub(r' +', ' ', text)
    return text.strip()


def _strip(text: str) -> str:
    """Normalise unicode and remove all whitespace — used for metric computation only."""
    return normalize_for_cer(text).replace(" ", "")


def _join_readable(texts) -> str:
    """Join box texts with blank lines between them, preserving internal whitespace."""
    return "\n\n".join(t.strip() for t in texts if t and t.strip())


def _ssu_n(ssu_id: str) -> int:
    """Extract reading-order index N from an ssu_id.

    ssu_masthead / ssu_other_* → -1 (sorts before numbered column content).
    ssu_N_col_M               → N
    """
    try:
        return int(ssu_id.split("_")[1])
    except (IndexError, ValueError):
        return -1


# ---------------------------------------------------------------------------
# Load static data
# ---------------------------------------------------------------------------
print("Loading gt_ssu_bboxes.csv …")
ssu_full = pd.read_csv(_SSU_CSV)
if "page_id" not in ssu_full.columns:
    ssu_full["page_id"] = ssu_full["filename"].str.removesuffix(".jpg")
ssu_full["ssu_n"] = ssu_full["ssu_id"].map(_ssu_n)

# GT parsing OCR parquets (spiritualist_gt_predictions_{om}_ocr.parquet)
print("Loading GT parsing OCR parquets …")
gt_ocr_parts = []
for f in sorted(_OCR_DIR.glob("spiritualist_gt_predictions_*_ocr.parquet")):
    om   = f.stem.removeprefix("spiritualist_gt_predictions_").removesuffix("_ocr")
    part = pd.read_parquet(f)
    part["ocr_model"]     = om
    part["parsing_model"] = "gt"
    gt_ocr_parts.append(part)
gt_ocr_df = pd.concat(gt_ocr_parts, ignore_index=True) if gt_ocr_parts else pd.DataFrame()
if not gt_ocr_df.empty:
    gt_ocr_df["page_id"] = gt_ocr_df["filename"].str.removesuffix(".jpg")
    gt_ocr_df["ssu_n"]   = gt_ocr_df["ssu_id"].map(_ssu_n)

# Non-GT parsing OCR parquets (spiritualist_{pm}_predictions_{om}_ocr.parquet)
print("Loading non-GT parsing OCR parquets …")
pred_ocr_parts = []
for f in sorted(_OCR_DIR.glob("*_ocr.parquet")):
    inner = f.stem.removeprefix("spiritualist_").removesuffix("_ocr")
    sep   = inner.index("_predictions_")
    pm    = inner[:sep]
    if pm == "gt":
        continue
    om   = inner[sep + len("_predictions_"):]
    part = pd.read_parquet(f)
    part["parsing_model"] = pm
    part["ocr_model"]     = om
    pred_ocr_parts.append(part)
pred_ocr_df = pd.concat(pred_ocr_parts, ignore_index=True) if pred_ocr_parts else pd.DataFrame()
if not pred_ocr_df.empty:
    pred_ocr_df["page_id"] = pred_ocr_df["filename"].str.removesuffix(".jpg")

pages          = sorted(ssu_full["page_id"].unique())
ocr_models     = sorted(gt_ocr_df["ocr_model"].unique())      if not gt_ocr_df.empty    else []
non_gt_parsers = sorted(pred_ocr_df["parsing_model"].unique()) if not pred_ocr_df.empty else []
parsing_models = ["gt"] + non_gt_parsers

print(f"Pages: {len(pages)}, OCR models: {ocr_models}, Parsing models: {parsing_models}")

_TEXT_GT_DIR.mkdir(parents=True, exist_ok=True)
_TEXT_PRED_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# GT string builder (annotated text, position-ordered)
# ---------------------------------------------------------------------------

def _sorted_gt(page: str) -> pd.Series:
    sub = ssu_full[ssu_full["page_id"] == page].sort_values(["ssu_n", "y", "x"])
    return sub["gt_text"].fillna("")


def _build_gt_string(page: str) -> str:
    """Annotated GT text, all whitespace stripped — for metrics."""
    return "".join(_strip(t) for t in _sorted_gt(page))


def _build_gt_readable(page: str) -> str:
    """Annotated GT text with whitespace preserved — for inspection."""
    return _join_readable(_sorted_gt(page))


# ---------------------------------------------------------------------------
# Predicted string builders
# ---------------------------------------------------------------------------

def _sorted_gt_parsing(page: str, om: str) -> pd.Series:
    if gt_ocr_df.empty:
        return pd.Series([], dtype=str)
    sub = gt_ocr_df[
        (gt_ocr_df["page_id"] == page) & (gt_ocr_df["ocr_model"] == om)
    ].sort_values(["ssu_n", "y", "x"])
    return sub["ocr_text"]


def _build_pred_string_gt_parsing(page: str, om: str) -> str:
    return "".join(_strip(t) for t in _sorted_gt_parsing(page, om))


def _build_pred_readable_gt_parsing(page: str, om: str) -> str:
    return _join_readable(_sorted_gt_parsing(page, om))


def _match_boxes_to_ssus(
    pred_rows: pd.DataFrame,
    ssu_page: pd.DataFrame,
    img_w: int,
    img_h: int,
) -> pd.DataFrame:
    """
    Assign each predicted box to the GT SSU it overlaps most with.
    Uses boxes_to_gt_ssu_map to rasterise GT SSUs; takes the majority
    non-zero pixel label under each predicted box.
    Boxes with no overlap receive NaN as their ssu_n.
    """
    ssu_page = ssu_page.reset_index(drop=True)
    ssu_page["_ssu_int"] = ssu_page.index + 1   # 1-indexed; 0 = background
    int_to_n = dict(zip(ssu_page["_ssu_int"], ssu_page["ssu_n"]))
    int_to_y = dict(zip(ssu_page["_ssu_int"], ssu_page["y"]))
    int_to_x = dict(zip(ssu_page["_ssu_int"], ssu_page["x"]))

    boxes  = ssu_page[["x", "y", "width", "height", "_ssu_int"]].to_dict("records")
    canvas = boxes_to_gt_ssu_map(boxes, img_w, img_h, ssu_id_key="_ssu_int")

    matched_ssu_ns, matched_ys, matched_xs = [], [], []
    for _, row in pred_rows.iterrows():
        x1 = max(0, int(round(float(row["x"]))))
        y1 = max(0, int(round(float(row["y"]))))
        x2 = min(img_w, int(round(float(row["x"]) + float(row["width"]))))
        y2 = min(img_h, int(round(float(row["y"]) + float(row["height"]))))
        if x2 <= x1 or y2 <= y1:
            matched_ssu_ns.append(np.nan)
            matched_ys.append(np.nan)
            matched_xs.append(np.nan)
            continue
        region  = canvas[y1:y2, x1:x2].ravel()
        nonzero = region[region != 0]
        if len(nonzero) == 0:
            matched_ssu_ns.append(np.nan)
            matched_ys.append(np.nan)
            matched_xs.append(np.nan)
        else:
            majority_int = int(np.bincount(nonzero).argmax())
            matched_ssu_ns.append(float(int_to_n.get(majority_int, np.nan)))
            matched_ys.append(float(int_to_y.get(majority_int, np.nan)))
            matched_xs.append(float(int_to_x.get(majority_int, np.nan)))

    pred_rows = pred_rows.copy()
    pred_rows["ssu_n"]    = matched_ssu_ns
    pred_rows["_match_y"] = matched_ys
    pred_rows["_match_x"] = matched_xs
    return pred_rows


def _ordered_pred(
    page: str,
    pm: str,
    om: str,
    ssu_page: pd.DataFrame,
    img_w: int,
    img_h: int,
) -> pd.Series:
    """Return OCR texts for a non-GT parsing model in SSU reading order."""
    if pred_ocr_df.empty:
        return pd.Series([], dtype=str)
    sub = pred_ocr_df[
        (pred_ocr_df["page_id"] == page)
        & (pred_ocr_df["parsing_model"] == pm)
        & (pred_ocr_df["ocr_model"] == om)
    ].copy()
    if sub.empty:
        return pd.Series([], dtype=str)
    sub = _match_boxes_to_ssus(sub, ssu_page, img_w, img_h)
    matched   = sub[sub["ssu_n"].notna()].sort_values(["ssu_n", "_match_y", "_match_x", "y"])
    unmatched = sub[sub["ssu_n"].isna()]
    return pd.concat([matched, unmatched], ignore_index=True)["ocr_text"]


def _build_pred_string(page, pm, om, ssu_page, img_w, img_h) -> str:
    return "".join(_strip(t) for t in _ordered_pred(page, pm, om, ssu_page, img_w, img_h))


def _build_pred_readable(page, pm, om, ssu_page, img_w, img_h) -> str:
    return _join_readable(_ordered_pred(page, pm, om, ssu_page, img_w, img_h))


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
records = []

# Pre-build GT strings per page (shared across all model combos)
print("Building GT strings …")
gt_strings: dict[str, str] = {}
for page in pages:
    gt_str = _build_gt_string(page)
    gt_strings[page] = gt_str
    (_TEXT_GT_DIR / f"{page}.txt").write_text(_build_gt_readable(page), encoding="utf-8")

for page in tqdm(pages, desc="pages"):
    ssu_page = ssu_full[ssu_full["page_id"] == page]
    img_w    = int(ssu_page["image_width"].iloc[0])
    img_h    = int(ssu_page["image_height"].iloc[0])
    gt_str   = gt_strings[page]
    n_gt     = len(gt_str)

    for om in ocr_models:
        for pm in parsing_models:
            if pm == "gt":
                pred_str     = _build_pred_string_gt_parsing(page, om)
                pred_readable = _build_pred_readable_gt_parsing(page, om)
            else:
                pred_str      = _build_pred_string(page, pm, om, ssu_page, img_w, img_h)
                pred_readable = _build_pred_readable(page, pm, om, ssu_page, img_w, img_h)

            (_TEXT_PRED_DIR / f"{page}_{pm}_{om}.txt").write_text(pred_readable, encoding="utf-8")

            n_pred = len(pred_str)

            cer_val      = jiwer_cer(gt_str, pred_str) if gt_str and pred_str else None
            gt_counter   = Counter(gt_str)
            pred_counter = Counter(pred_str)
            spacer_val   = spacer(gt_counter, pred_counter)
            cdd_val      = cdd_decomp({"gt": gt_str, "total": pred_str}).d_total

            records.append({
                "page":          page,
                "parsing_model": pm,
                "ocr_model":     om,
                "cer":           cer_val,
                "spacer_total":  spacer_val,
                "cdd_total":     cdd_val,
                "n_gt_chars":    n_gt,
                "n_pred_chars":  n_pred,
            })

out_df = pd.DataFrame(records)
_OUT.parent.mkdir(parents=True, exist_ok=True)
out_df.to_parquet(_OUT, index=False)
print(f"\nSaved {len(out_df)} rows → {_OUT}")
print(f"GT text files  → {_TEXT_GT_DIR}/")
print(f"Pred text files → {_TEXT_PRED_DIR}/")
print(out_df.groupby("parsing_model")[["cer", "spacer_total", "cdd_total"]].median().round(4))
